DROP TABLE CHANNEL;

CREATE TABLE CHANNEL (
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (ID));

DROP TABLE DM;

CREATE TABLE DM (
    ID INt NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (ID));


